# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_overdisp_block_improved <- function(boot_sparse, start_col, end_col, n_boot, n_genes, eps = 1e-8, pseudocount = 0.1) {
    .Call(`_scAmbi_compute_overdisp_block_improved`, boot_sparse, start_col, end_col, n_boot, n_genes, eps, pseudocount)
}

